#!/bin/bash
set -x
if [ ! -d $OPENSHIFT_DATA_DIR/gradle-2.4 ]
then
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
    wget http://services.gradle.org/distributions/gradle-2.4-bin.zip
    unzip gradle-2.4-bin.zip
    rm -f gradle-2.4-bin.zip
fi
