spring:
    datasource:
        platform: hsqldb
    thymeleaf:
        # Allow Thymeleaf templates to be reloaded at dev time
        cache: false
    resources:
        chain:
            enabled: true
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
    
security:
    csrf:
        tokenRepository:
            headerName: X-XSRF-TOKEN
    oauth2:
        client:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            clientAuthenticationScheme: query
            scope: profile email
        resource:
            userInfoUri: https://www.googleapis.com/plus/v1/people/me
            preferTokenInfo: false

server:
    tomcat:
        access_log_enabled: true
        tomcat.basedir: target/tomcat

---

spring:
    profiles: prod
    datasource:
        url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/padirbtuves
        username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
        password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}
        initialize: false
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
    file: ${OPENSHIFT_LOG_DIR}/spring.log
